//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersimosMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzMedEntities : DbContext
    {
        public AzMedEntities()
            : base("name=AzMedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<EstadoOC> EstadoOC { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<modulo> modulo { get; set; }
        public virtual DbSet<ObraSocial> ObraSocial { get; set; }
        public virtual DbSet<operaciones> operaciones { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Profesionales> Profesionales { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rol_operacion> rol_operacion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<DetalleSolp> DetalleSolp { get; set; }
        public virtual DbSet<EstadoSolp> EstadoSolp { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Solped> Solped { get; set; }
        public virtual DbSet<DetalleOC> DetalleOC { get; set; }
        public virtual DbSet<OrdenesCompras> OrdenesCompras { get; set; }
        public virtual DbSet<Cotizaciones> Cotizaciones { get; set; }
        public virtual DbSet<Estudios> Estudios { get; set; }
        public virtual DbSet<TurnosEstudios> TurnosEstudios { get; set; }
    }
}
