//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersimosMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cotizaciones
    {
        public int id { get; set; }
        [Required]
        public Nullable<System.DateTime> Fecha { get; set; }
        [Required]
        public Nullable<bool> Estado { get; set; }
        [Required]
        public Nullable<int> Precio_Unitario { get; set; }
        [Required]
        public Nullable<int> Proveedor { get; set; }
        [Required]
        public Nullable<int> Solp { get; set; }
        [Required]

        public virtual Solped Solped { get; set; }
        [Required]
        public virtual Proveedor Proveedor1 { get; set; }
    }
}
