//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersimosMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DetalleSolp
    {
        public int id { get; set; }
        [Required]
        public Nullable<int> Solped { get; set; }
        [Required]
        public Nullable<int> Material { get; set; }
        [Required]
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Solped Solped1 { get; set; }
        public virtual Material Material1 { get; set; }
    }
}
