//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersimosMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrdenesCompras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesCompras()
        {
            this.DetalleOC = new HashSet<DetalleOC>();
        }
    
        public int id { get; set; }
        [Required]
        public Nullable<int> Proveedor { get; set; }
        [Required]
        public Nullable<int> Estado { get; set; }
        [Required]
        public Nullable<System.DateTime> Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOC> DetalleOC { get; set; }
        public virtual EstadoOC EstadoOC { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
    }
}
