//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersimosMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TurnosEstudios
    {
        public int id { get; set; }
        [Required]
        public Nullable<int> Tipo_Estudios { get; set; }
        [Required]
        public Nullable<int> Paciente { get; set; }
        [Required]

        public virtual Estudios Estudios { get; set; }
        [Required]
        public virtual Pacientes Pacientes { get; set; }
    }
}
